### ISSUE TITLE
Error in sudo npm install -g zos

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-cli#231] opened 2018-05-26 14:17 UTC
Installing globally with `sudo npm install -g zos` may fail due to a permissions error.

In the meantime consider installing locally with `npm install zos` (no `-g`), and then running with either:
- `npx zos` (npm >= 5.2.0)
- `node_modules/.bin/zos`

**Comment by Grana69** [comment] 2018-05-30 19:59
Fix with:
npm install zos -g --unsafe-perm=true --allow-root

**Comment by spalladino** [comment] 2018-07-04 22:56
The problem seems to be caused by a few dependencies from the CLI that install from git directly. 

I tried on a fresh ubuntu box to install `sudo npm i -g babel-cli`, which worked fine, but when trying `zos` it failed upon a git clone operation. In particular, running the following command fails due to permission errors:
```bash
sudo npm i -g "git+https://github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934"
```

Note that these git dependencies are present in our package-lock file since they are used by web3 (for instance) and we cannot remove them.

---

The best solution IMO is to actually follow the steps described in the npm documentation to [fix permission errors](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) and change the default global directory, so global packages can be installed without `sudo`. I'd suggest closing this issue, since there is nothing we can currently change from the CLI.

**Closed** 2018-07-05 15:06 UTC
Labels: kind:bug, size:8
