### ISSUE TITLE
zos push command prints wrong error message if from parameter is empty

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#248] opened 2018-06-07 16:44 UTC
If you do a `zos push` command with an empty `--from` parameter, it tells you that you're missing the network name.  In the sample below, I forgot to export the OWNER variable during another pass at the Basil tutorial.  Look at the results below:

```sh
$  npx zos push --from $OWNER --network local
A network name must be provided to execute the requested action.
$  env | grep OWNER
# (no results since I forgot to set it.  Setting it now)
$  export OWNER=0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
$  npx zos push --from $OWNER --network local
Compiling contracts
...```

**Comment by facuspagnuolo** [comment] 2018-06-25 18:50
Could not reproduce, if I call `zos push --from $OWNER --network local` without exporting something to `$OWNER` I get the helper doc outputted. Are you sure about this?

**Comment by roschler** [comment] 2018-06-25 19:42
Hi Facundo,

Do you get a helper doc if you type just `zos` and nothing else except the Enter key, do you see a helper doc, or nothing at all?

**Comment by facuspagnuolo** [comment] 2018-06-25 19:59
We just added that feature but it is not released yet

**Comment by facuspagnuolo** [comment] 2018-07-14 01:54
I'm closing this one since we could not reproduce it

**Closed by facuspagnuolo** 2018-07-14 01:54 UTC
Labels: kind:discussion, topic:dx

**Comment by roschler** [comment] 2018-07-14 02:41
It happened me again today when I started a new shell and forgot to put my public address in the `OWNER` environment variable.  I'm using **zos 1.0.0**:

```sh
$ zos --version
1.0.0
$  env | alias OWNER
bash: alias: OWNER: not found
$  zos push --from $OWNER --network local
A network name must be provided to execute the requested action.
```
As you can see, I do provide a network name ("local") along with the `--network` command line flag.  Despite that ZOS complains that a network name was not supplied instead of recognizing that it was the `--from` argument that was not provided (because the $OWNER environment variable is not set).

Now I run it again after assigning `$OWNER`:
```sh
$  export OWNER=0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
$  zos push --from $OWNER --network local
Compiling contracts
Compiling ./contracts/EtherBandBattlesManager.sol...
Compiling ./node_modules/openzeppelin-zos/contracts/lifecycle/Pausable.sol...
Compiling ./node_modules/openzeppelin-zos/contracts/math/SafeMath.sol...
Compiling ./node_modules/openzeppelin-zos/contracts/ownership/Ownable.sol...
Compiling ./node_modules/zos-lib/contracts/migrations/Migratable.sol...
Writing artifacts to ./build/contracts

Setting stdlib 0...
0xc89ce4735882c9f0f0fe26686c53074e09b0d550
Successfully written zos.local.json
```
If you take a look at the ZOS client source code that analyzes the command line arguments fpr tjat a[[, you'll see the problem is due to the way the program is parsing out the command line arguments.  I have a forked copy of the ZOS client on my system.
